baseURL = "https://raganato.github.io/"
languageCode = "en-us"
title = "Alessandro Raganato"
theme = "personal-web"
copyright="© Alessandro Raganato"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Alessandro Raganato"
  sub = "alessandro.raganato@helsinki.fi"


[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '/images/sidebar.jpg' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/raganato.jpg" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
#  github = "https://github.com/raganato"
  twitter = "https://twitter.com/Ale_Raganato"
  googlescholar = "https://scholar.google.com/citations?user=aek0emAAAAAJ&hl=en"

[params.contact]
  email = ""
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/about/"
  weight = -130

[[menu.main]]
  identifier = "publications"
  name = "Publications"
  title = "Publications"
  url = "/publications/"
  weight = -120

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  title = "Projects"
  url = "/projects/"
  weight = -110

[[menu.main]]
  identifier = "teaching"
  name = "Teaching"
  title = "Teaching"
  url = "/teaching/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
